### ISSUE TITLE
Access to cancel button

### ISSUE THREAD

**Issue by leteach** [duhwcarvalho/react-native-picker-box#1]
Thanks for a great library. Can we get some props for changing the cancel button?

**Comment by Nodirbek3d** [comment]
I agree, library is great, but we need option to modify cancel button title

**Comment by duhwcarvalho** [comment]
Hi @leteach thanks for the suggestion!

@Nodirbek3d I noticed you're working on it.

Can you submit a PR with this implementation?

- edit 
I did not receive answer, took the initiative for submit a PR with this implementation
