### ISSUE TITLE
'_onValueChange' pass item.label not item.value

### ISSUE THREAD

**Issue by hsk-kr** [duhwcarvalho/react-native-picker-box#10]
```javascript
_onValueChange = item => {
        this.setState({
            selectedValue: item.value
        })

        this.props.onValueChange(item.label)
        
        this._closePicker()
    }
```

I expected an argument of onValueChange is a value of an item. but It's not. It's a label of an item.

**Comment by duhwcarvalho** [comment]
Hey @hsk-kr 
I think it would be great, I'll do it. Thanks for the suggestion!

you can get value per methods, use refs for open Picker.
`this.myref.state.selectedValue`

**Comment by hsk-kr** [comment]
@duhwcarvalho 

That's glad to hear that :) 
I modified your module and then I'm using it. 
Thank you for beautiful module :D

And Plus
There was a problem that doesn't update state when props has been changed.
Other components'd been updated successfully but PIckerBox didn't.
But I didn't spend time for that so It couldn't be a problem. I just comment it.
below code isn't good code. actually I think It's terrible code. :( 
but I didn't want to spend it time more so I just moved in. 
anyway, thank you for the good component!!

```javascript
componentDidUpdate(prevProps, nextState) {
        // CUSTOMIZE
        // If data doesn't equal to data of current prop, update it.
        let isEqual = true;
        prevProps.data.forEach((v, i) => {
            if (v !== this.state.data[i]) {
                isEqual = false;
            }
        })

        if (!isEqual) {
            this.setState({
                data: prevProps.data
            });
        }

        nextState.visible !== this.state.visible && this._animatePicker()
    }
```

**Comment by duhwcarvalho** [comment]
@hsk-kr 
Thank you too!

you can try replacing your code with extraData from FlatList

```
<FlatList
  bounces={false}
  style={styles.flat}
  contentContainerStyle={styles.contentFlat}
  data={this.props.data} // 
  extraData ={this.props} // this.props or this.props.data
  keyExtractor={(item, index) => index+''}
  renderItem={this._renderItem}
/>
```
